spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          forwarded:
            enabled: true
#          routes:
#            - id: patients-service
#              uri: lb://patients-service
#              predicates:
#                - Path=/patients-service/**
#              filters:
#                - AddRequestHeader=Authorization, Basic dXNlcjpwYXNzd29yZA==
#            - id : front-service
#              uri: lb://front-service
#              predicates:
#                - Path=/patients/**
#              filters:
#                - StripPrefix=1
#              order: -1
    loadbalancer:
      cache:
        ttl: 5s

eureka:
  client:
    registry-fetch-interval-seconds: 5
    fetch-registry: true
    register-with-eureka: true